apiVersion: v1
kind: Service
metadata:
  name: {{ include "pnHelm.fullname" . }}
  labels:
    {{- include "pnHelm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pnHelm.selectorLabels" . | nindent 4 }}
